# Generated by Django 4.2.2 on 2023-07-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='sname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
