# Generated by Django 4.2.2 on 2023-07-26 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_userprofiles_applicatindate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofiles',
            options={'verbose_name_plural': 'Userprofiles'},
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='profileowner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_ownership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='sirname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
