# Generated by Django 4.2.2 on 2023-07-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofiles_options_userprofiles_profileowner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofiles',
            old_name='profileowner',
            new_name='name',
        ),
    ]
