# Generated by Django 4.2.2 on 2023-07-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_profileowner_userprofiles_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userprofiles',
        ),
    ]
