# Generated by Django 4.2.2 on 2023-08-02 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_delete_userprofiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='profile_photo/%Y/%m/%d')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('sir_name', models.CharField(max_length=255)),
                ('user_bio', models.TextField(blank=True, null=True)),
                ('id_no', models.CharField(max_length=255)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('self_employed', 'Self-employed'), ('student', 'Student'), ('other', 'Other')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not_specified', "I'd rather not disclose")], max_length=15)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('highest_level_of_education', models.CharField(choices=[('high_school', 'High School'), ('college', 'College'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('doctorate', 'Doctorate'), ('other', 'Other')], max_length=20)),
                ('town_of_residence', models.TextField()),
                ('po_box', models.BigIntegerField()),
                ('zip_code', models.BigIntegerField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone_no', models.TextField()),
                ('alternative_phone_no', models.TextField()),
                ('nok_email', models.EmailField(max_length=254)),
                ('nok_phone_no', models.TextField()),
                ('nok_alternative_phone_no', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
