# Generated by Django 4.2.2 on 2023-08-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='curriculum_vitae',
            field=models.FileField(blank=True, null=True, upload_to='cv/%Y/%m/%d'),
        ),
    ]
