# Generated by Django 4.2.2 on 2023-08-02 21:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_certificates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('application_letter', models.TextField()),
                ('additional_certificates', models.FileField(blank=True, upload_to='additional_certificates/%Y/%m/%d')),
                ('application_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
    ]
