# Generated by Django 4.2.2 on 2023-08-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_letter',
            field=models.FileField(upload_to='additional_certificates/%Y/%m/%d'),
        ),
    ]
