# Generated by Django 4.2.2 on 2023-08-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_jobapplication_application_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_letter',
            field=models.FileField(upload_to='application_letter/%Y/%m/%d'),
        ),
    ]
