# Generated by Django 4.2.2 on 2023-08-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_jobapplication_application_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_image', models.ImageField(upload_to='portal_photo/%Y/%m/%d')),
            ],
        ),
    ]
