# Generated by Django 4.2.2 on 2023-06-19 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_remove_item_id_remove_item_not_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='department',
        ),
        migrations.RemoveField(
            model_name='item',
            name='job_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
