# Generated by Django 4.2.2 on 2023-06-19 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='position',
            new_name='name',
        ),
    ]
