# Generated by Django 4.2.2 on 2023-06-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_item_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='duties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
